# Generated by Django 5.0.1 on 2024-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.IntegerField(default=0),
        ),
    ]
